// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATLzMgHBxE_Xbk4X8PptElV1i-qiMYJdQ',
    appId: '1:699524638394:web:b62d43a65f2e7898450483',
    messagingSenderId: '699524638394',
    projectId: 'reddit-clone-522de',
    authDomain: 'reddit-clone-522de.firebaseapp.com',
    storageBucket: 'reddit-clone-522de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF2zsIaG9XeG6uqmaKxuDO97mdcgaHX1w',
    appId: '1:699524638394:android:ecfdc9084779804b450483',
    messagingSenderId: '699524638394',
    projectId: 'reddit-clone-522de',
    storageBucket: 'reddit-clone-522de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGxQeXpKKUBpPhrSBqLnshqlRRh_JxFLE',
    appId: '1:699524638394:ios:33cab96634c92f48450483',
    messagingSenderId: '699524638394',
    projectId: 'reddit-clone-522de',
    storageBucket: 'reddit-clone-522de.appspot.com',
    iosClientId: '699524638394-keah4tl29i7c328dv2k632if88pfhme7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
